# Generated by Django 5.0.6 on 2024-06-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('permission', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('institiut', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_activ', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RadioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('verdacht_diagnose', models.CharField(max_length=255)),
                ('körper_teil', models.CharField(max_length=255)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendairadio.case')),
            ],
        ),
        migrations.CreateModel(
            name='RadioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendairadio.radioimage')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255)),
                ('date_analysis', models.DateField()),
                ('time_analysis', models.TimeField()),
                ('docker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendairadio.docker')),
                ('radioInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendairadio.radioinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendairadio.user')),
            ],
        ),
    ]
