# Generated by Django 5.0.6 on 2024-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='sex',
            field=models.CharField(choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
