# Generated by Django 5.0.6 on 2024-06-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0002_case_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioimage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='radioimage',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
