# Generated by Django 5.0.6 on 2024-06-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0003_alter_radioimage_date_alter_radioimage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioinfo',
            name='position',
            field=models.CharField(choices=[('A', 'anterior'), ('P', 'posterior'), ('S', 'superior'), ('I', 'inferior '), ('d', 'dexter '), ('S', 'sinister ')], max_length=1),
        ),
    ]
