# Generated by Django 5.0.6 on 2024-06-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0005_remove_radioinfo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioinfo',
            name='size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
