# Generated by Django 5.0.6 on 2024-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0006_radioinfo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='casename',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
