# Generated by Django 5.0.6 on 2024-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0007_alter_case_casename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radioimage',
            name='körper_teil',
        ),
        migrations.RemoveField(
            model_name='radioimage',
            name='verdacht_diagnose',
        ),
        migrations.AddField(
            model_name='case',
            name='körper_teil',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='verdacht_diagnose',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
