# Generated by Django 5.0.6 on 2024-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0009_remove_radioimage_case_remove_radioinfo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='date_analysis',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='time_analysis',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
