# Generated by Django 5.0.6 on 2024-06-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0010_alter_analysisresult_date_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='docker',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='user',
        ),
    ]
