# Generated by Django 5.0.6 on 2024-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0011_remove_analysisresult_docker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='start_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
