# Generated by Django 5.0.6 on 2024-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0012_docker_start_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docker',
            old_name='start_id',
            new_name='docker_ip',
        ),
        migrations.AddField(
            model_name='docker',
            name='docker_port',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radioinfo',
            name='position',
            field=models.CharField(choices=[('anterior', 'anterior'), ('posterior', 'posterior'), ('superior', 'superior'), ('inferior', 'inferior '), ('dexter', 'dexter '), ('sinister', 'sinister ')], max_length=25),
        ),
    ]
