# Generated by Django 5.0.6 on 2024-06-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0013_rename_start_id_docker_docker_ip_docker_docker_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='docker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendairadio.docker'),
            preserve_default=False,
        ),
    ]
