# Generated by Django 5.0.6 on 2024-06-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0015_rename_is_activ_user_is_admin_remove_user_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
