# Generated by Django 5.0.6 on 2024-06-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0016_user_username_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
