# Generated by Django 5.0.6 on 2024-06-20 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendairadio', '0017_rename_is_admin_user_is_staff_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
